package cloud.masteroflie.sgpa.enums;

import cloud.masteroflie.sgpa.models.Perfil;
import jakarta.persistence.CascadeType;
import jakarta.persistence.OneToMany;
import lombok.Getter;

import java.util.List;

@Getter
public enum PermissionsRole {
    PROFILE_CREATE("PROFILE_CREATE"),
    PROFILE_EDIT("PROFILE_EDIT"),
    PROFILE_ASSIGN("PROFILE_ASSIGN"),
    PROFILE_TOGGLE("PROFILE_TOGGLE"),
    PROFILE_VIEW("PROFILE_VIEW"),

    USER_CREATE("USER_CREATE"),
    USER_EDIT("USER_EDIT"),
    USER_TOGGLE("USER_TOGGLE"),
    USER_VIEW("USER_VIEW"),

    SECTOR_CREATE("SECTOR_CREATE"),
    SECTOR_EDIT("SECTOR_EDIT"),
    SECTOR_DELETE("SECTOR_DELETE"),
    SECTOR_TOGGLE("SECTOR_TOGGLE"),
    SECTOR_VIEW("SECTOR_VIEW"),

    SERVICE_CREATE("SERVICE_CREATE"),
    SERVICE_EDIT("SERVICE_EDIT"),
    SERVICE_DELETE("SERVICE_DELETE"),
    SERVICE_TOGGLE("SERVICE_TOGGLE"),
    SERVICE_VIEW("SERVICE_VIEW"),

    DEPARTMENT_CREATE("DEPARTMENT_CREATE"),
    DEPARTMENT_EDIT("DEPARTMENT_EDIT"),
    DEPARTMENT_DELETE("DEPARTMENT_DELETE"),
    DEPARTMENT_TOGGLE("DEPARTMENT_TOGGLE"),
    DEPARTMENT_ASSIGN("DEPARTMENT_ASSIGN"),
    DEPARTMENT_VIEW("DEPARTMENT_VIEW"),

    PROCESS_CREATE("PROCESS_CREATE"),
    PROCESS_EDIT("PROCESS_EDIT"),
    PROCESS_STATUS_CHANGE("PROCESS_STATUS_CHANGE"),

    REQUESTER_EDIT("REQUESTER_EDIT"),
    REQUESTER_PASSWORD_CHANGE("REQUESTER_PASSWORD_CHANGE"),


    APPLICATION_EDIT("APPLICATION_EDIT");


    private String role;

    PermissionsRole(String role) {
        this.role = role;
    }
}


